In [2]:
import pandas as pd

df = pd.read_csv("students.csv")

print(df)

     Name Department  Gender  Marks  Attendance
0   Rahul        BCA    Male     78          85
1   Priya        BCA  Female     92          94
2    Arun        BCA    Male     56          72
3   Sneha        BCA  Female     88          91
4   Kiran        BCA    Male     67          78
5  Anjali        BCA  Female     95          96
6    Ravi        BCA    Male     39          65
7    Neha        BCA  Female     73          82
8    Aman        BCA    Male     81          88
9   Pooja        BCA  Female     89          93

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Department  10 non-null     object
 2   Gender      10 non-null     object
 3   Marks       10 non-null     int64
 4   Attendance  10 non-null     int64
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes
None

In [4]:
df.sort_values("Marks")

     Name Department  Gender  Marks  Attendance
6    Ravi        BCA    Male     39          65
2    Arun        BCA    Male     56          72
4   Kiran        BCA    Male     67          78
7    Neha        BCA  Female     73          82
0   Rahul        BCA    Male     78          85
8    Aman        BCA    Male     81          88
3   Sneha        BCA  Female     88          91
9   Pooja        BCA  Female     89          93
1   Priya        BCA  Female     92          94
5  Anjali        BCA  Female     95          96

In [5]:
df.sort_values("Marks", ascending=False)

     Name Department  Gender  Marks  Attendance
5  Anjali        BCA  Female     95          96
1   Priya        BCA  Female     92          94
9   Pooja        BCA  Female     89          93
3   Sneha        BCA  Female     88          91
8    Aman        BCA    Male     81          88
0   Rahul        BCA    Male     78          85
7    Neha        BCA  Female     73          82
4   Kiran        BCA    Male     67          78
2    Arun        BCA    Male     56          72
6    Ravi        BCA    Male     39          65

In [10]:
df.sort_values("Marks", ascending=False).head(3)

     Name Department  Gender  Marks  Attendance
5  Anjali        BCA  Female     95          96
1   Priya        BCA  Female     92          94
9   Pooja        BCA  Female     89          93

In [7]:
df.sort_values("Marks", ascending=False).tail(3)

    Name Department Gender  Marks  Attendance
4  Kiran        BCA   Male     67          78
2   Arun        BCA   Male     56          72
6   Ravi        BCA   Male     39          65

In [12]:
df.nlargest(5, "Marks")

     Name Department  Gender  Marks  Attendance
5  Anjali        BCA  Female     95          96
1   Priya        BCA  Female     92          94
9   Pooja        BCA  Female     89          93
3   Sneha        BCA  Female     88          91
8    Aman        BCA    Male     81          88

In [13]:
df.nsmallest(3, "Marks")

    Name Department Gender  Marks  Attendance
6   Ravi        BCA   Male     39          65
2   Arun        BCA   Male     56          72
4  Kiran        BCA   Male     67          78

In [20]:
df.sort_values("Attendance", ascending=False)

     Name Department  Gender  Marks  Attendance  Rank
5  Anjali        BCA  Female     95          96   1.0
1   Priya        BCA  Female     92          94   2.0
9   Pooja        BCA  Female     89          93   3.0
3   Sneha        BCA  Female     88          91   4.0
8    Aman        BCA    Male     81          88   5.0
0   Rahul        BCA    Male     78          85   6.0
7    Neha        BCA  Female     73          82   7.0
4   Kiran        BCA    Male     67          78   8.0
2    Arun        BCA    Male     56          72   9.0
6    Ravi        BCA    Male     39          65  10.0

In [17]:
df.sort_values(
    ["Gender", "Marks"],
    ascending=[True, True]
)

     Name Department  Gender  Marks  Attendance
7    Neha        BCA  Female     73          82
3   Sneha        BCA  Female     88          91
9   Pooja        BCA  Female     89          93
1   Priya        BCA  Female     92          94
5  Anjali        BCA  Female     95          96
6    Ravi        BCA    Male     39          65
2    Arun        BCA    Male     56          72
4   Kiran        BCA    Male     67          78
0   Rahul        BCA    Male     78          85
8    Aman        BCA    Male     81          88

In [18]:
df["Rank"] = df["Marks"].rank(
    ascending=False,
    method="min"
)

In [19]:
df

     Name Department  Gender  Marks  Attendance  Rank
0   Rahul        BCA    Male     78          85   6.0
1   Priya        BCA  Female     92          94   2.0
2    Arun        BCA    Male     56          72   9.0
3   Sneha        BCA  Female     88          91   4.0
4   Kiran        BCA    Male     67          78   8.0
5  Anjali        BCA  Female     95          96   1.0
6    Ravi        BCA    Male     39          65  10.0
7    Neha        BCA  Female     73          82   7.0
8    Aman        BCA    Male     81          88   5.0
9   Pooja        BCA  Female     89          93   3.0

In [21]:
df.sort_values("Rank")

     Name Department  Gender  Marks  Attendance  Rank
5  Anjali        BCA  Female     95          96   1.0
1   Priya        BCA  Female     92          94   2.0
9   Pooja        BCA  Female     89          93   3.0
3   Sneha        BCA  Female     88          91   4.0
8    Aman        BCA    Male     81          88   5.0
0   Rahul        BCA    Male     78          85   6.0
7    Neha        BCA  Female     73          82   7.0
4   Kiran        BCA    Male     67          78   8.0
2    Arun        BCA    Male     56          72   9.0
6    Ravi        BCA    Male     39          65  10.0

In [22]:
df[
    (df["Marks"] >= 80) &
    (df["Attendance"] >= 85)
].sort_values("Marks", ascending=False)

     Name Department  Gender  Marks  Attendance  Rank
5  Anjali        BCA  Female     95          96   1.0
1   Priya        BCA  Female     92          94   2.0
9   Pooja        BCA  Female     89          93   3.0
3   Sneha        BCA  Female     88          91   4.0
8    Aman        BCA    Male     81          88   5.0

In [24]:
df.sort_values(
    ["Attendance", "Marks"],
    ascending=[False, False]
).head(3)

     Name Department  Gender  Marks  Attendance  Rank
5  Anjali        BCA  Female     95          96   1.0
1   Priya        BCA  Female     92          94   2.0
9   Pooja        BCA  Female     89          93   3.0

In [25]:
df.loc[df.groupby("Gender")["Marks"].idxmax()]

     Name Department  Gender  Marks  Attendance  Rank
5  Anjali        BCA  Female     95          96   1.0
8    Aman        BCA    Male     81          88   5.0

In [31]:
selected_columns = ["Rank", "Name", "Gender", "Marks", "Attendance"]

top_performers = df[
    (df["Marks"] >= 75) &
    (df["Attendance"] >= 80)
].sort_values("Marks", ascending=False)

print(top_performers[selected_columns])

   Rank    Name  Gender  Marks  Attendance
5   1.0  Anjali  Female     95          96
1   2.0   Priya  Female     92          94
9   3.0   Pooja  Female     89          93
3   4.0   Sneha  Female     88          91
8   5.0    Aman    Male     81          88
0   6.0   Rahul    Male     78          85

In [32]:
df.loc[df.groupby("Gender")["Marks"].idxmax()]

     Name Department  Gender  Marks  Attendance  Rank
5  Anjali        BCA  Female     95          96   1.0
8    Aman        BCA    Male     81          88   5.0

In [33]:
selected_columns = ["Name", "Gender", "Marks", "Attendance", "Rank"]

top_by_gender = df.loc[
    df.groupby("Gender")["Marks"].idxmax(),
    selected_columns
]

print(top_by_gender)

     Name  Gender  Marks  Attendance  Rank
5  Anjali  Female     95          96   1.0
8    Aman    Male     81          88   5.0

In [34]:
selected_columns = ["Name", "Gender", "Marks", "Attendance", "Rank"]

top_by_gender = df.loc[
    df.groupby("Department")["Marks"].idxmax(),
    selected_columns
]

print(top_by_gender)

     Name  Gender  Marks  Attendance  Rank
5  Anjali  Female     95          96   1.0