In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("student_performance.csv")

df

     Name Department  Gender  Marks  Attendance
0   Rahul        BCA    Male     78          85
1   Priya        BCA  Female     92          94
2    Arun        BCA    Male     56          72
3   Sneha        BCA  Female     88          91
4   Kiran        BCA    Male     67          78
5  Anjali        BCA  Female     95          96
6    Ravi        BCA    Male     39          65
7    Neha        BCA  Female     73          82
8    Aman        BCA    Male     81          88
9   Pooja        BCA  Female     89          93

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Department  10 non-null     object
 2   Gender      10 non-null     object
 3   Marks       10 non-null     int64
 4   Attendance  10 non-null     int64
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [5]:
df.describe()

          Marks  Attendance
count  10.00000   10.000000
mean   75.80000   84.400000
std    17.69369   10.189319
min    39.00000   65.000000
25%    68.50000   79.000000
50%    79.50000   86.500000
75%    88.75000   92.500000
max    95.00000   96.000000

In [6]:
df.groupby("Gender")["Marks"].mean()

Gender
Female    87.4
Male      64.2
Name: Marks, dtype: float64

In [7]:
df.groupby("Gender")["Marks"].agg(["mean", "max", "min", "count"])

        mean  max  min  count
Gender
Female  87.4   95   73      5
Male    64.2   81   39      5

In [8]:
df.groupby("Gender")[["Marks", "Attendance"]].mean()

        Marks  Attendance
Gender
Female   87.4        91.2
Male     64.2        77.6

In [9]:
df.groupby("Department")[["Marks", "Attendance"]].mean()

            Marks  Attendance
Department
BCA          75.8        84.4

In [10]:
df.groupby("Gender")["Attendance"].mean()

Gender
Female    91.2
Male      77.6
Name: Attendance, dtype: float64

In [11]:
df.groupby("Gender")["Marks"].max()

Gender
Female    95
Male      81
Name: Marks, dtype: int64

In [12]:
df.groupby("Gender")["Marks"].min()

Gender
Female    73
Male      39
Name: Marks, dtype: int64

In [25]:
df.groupby("Gender").agg({
    "Marks": ["mean", "max", "min"],
    "Attendance": "mean",
    "Name": "count"
})

       Marks         Attendance  Name
        mean max min       mean count
Gender
Female  87.4  95  73       91.2     5
Male    64.2  81  39       77.6     5

In [27]:
df[df["Marks"] >= 80]

     Name Department  Gender  Marks  Attendance
1   Priya        BCA  Female     92          94
3   Sneha        BCA  Female     88          91
5  Anjali        BCA  Female     95          96
8    Aman        BCA    Male     81          88
9   Pooja        BCA  Female     89          93

In [28]:
df[df["Marks"] >= 80]["Marks"].mean()

89.0

In [30]:
df.groupby("Gender")["Name"].count()

Gender
Female    5
Male      5
Name: Name, dtype: int64

In [31]:
df.loc[df.groupby("Gender")["Marks"].idxmax()]

     Name Department  Gender  Marks  Attendance
5  Anjali        BCA  Female     95          96
8    Aman        BCA    Male     81          88

In [32]:
high_performers = df[
    (df["Marks"] >= 80) &
    (df["Attendance"] >= 85)
]

high_performers.groupby("Gender")["Name"].count()

Gender
Female    4
Male      1
Name: Name, dtype: int64

In [34]:
df["Result"] = df["Marks"].apply(
    lambda x: "Pass" if x >= 40 else "Fail"
)

In [35]:
df.groupby(["Gender", "Result"])["Name"].count()

Gender  Result
Female  Pass      5
Male    Fail      1
        Pass      4
Name: Name, dtype: int64

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Department  10 non-null     object
 2   Gender      10 non-null     object
 3   Marks       10 non-null     int64
 4   Attendance  10 non-null     int64
 5   Result      10 non-null     object
dtypes: int64(2), object(4)
memory usage: 612.0+ bytes

In [37]:
df

     Name Department  Gender  Marks  Attendance Result
0   Rahul        BCA    Male     78          85   Pass
1   Priya        BCA  Female     92          94   Pass
2    Arun        BCA    Male     56          72   Pass
3   Sneha        BCA  Female     88          91   Pass
4   Kiran        BCA    Male     67          78   Pass
5  Anjali        BCA  Female     95          96   Pass
6    Ravi        BCA    Male     39          65   Fail
7    Neha        BCA  Female     73          82   Pass
8    Aman        BCA    Male     81          88   Pass
9   Pooja        BCA  Female     89          93   Pass

In [38]:
df.loc[df.groupby("Gender")["Marks"].idxmax()]

     Name Department  Gender  Marks  Attendance Result
5  Anjali        BCA  Female     95          96   Pass
8    Aman        BCA    Male     81          88   Pass

In [39]:
gender_summary = df.groupby("Gender").agg({
    "Name": "count",
    "Marks": ["mean", "max", "min"],
    "Attendance": ["mean", "max"]
})

print(gender_summary)

        Name Marks         Attendance
       count  mean max min       mean max
Gender
Female     5  87.4  95  73       91.2  96
Male       5  64.2  81  39       77.6  88